language: rust

rust:
  - stable
  - nightly

addons:
  apt:
    packages:
      - debhelper
      - fakeroot

cache:
  cargo: true

script:
  - cargo build --all
  - cargo test --all

jobs:
  allow_failures:
    - rust: nightly-2019-09-03
  include:
    - stage: clippy lints
      rust: nightly-2019-09-03
      before_install:
        - rustup component add clippy
      script:
        - cargo clippy --all -- -D warnings

    - stage: release
      if: tag IS present
      script:
        - rm -f "./pkg/deb/*.deb" "./pkg/bin/*.tar.xz"
        - ./pkg/deb/makedeb
        - ./pkg/bin/makebin
      deploy:
        provider: releases

        file_glob: true
        file:
          - "./pkg/deb/*.deb"
          - "./pkg/bin/*.tar.xz"

        api_key:
          secure: ywNJL+pBOop/e/bCGKa02pZFHZfxwAEGy5+erAkiETFvqBR75i8fqMdnD8/s7Xj+0bXtzcZO8M9RpzGkcQpFLuULoyAI0aIXF6JVj3hMGN38NfcsPMhVK81ynM984IYfos2Av7uHNtHxqO1/W3N8fmThzj6/WwPknidMTHXXLwzOZyqX5ScuLX5jzll4nRad6KEmybdJqlC4J6UnT1YXCK1KSBGNM6BafrpZ69JcJqPuoLxn7is5hAOn4byp9NADOkmGTOQ3kIIbIbe4Khybe/g3GnhNnrlYQUXiC/ca88AMASdgarc7komsUovqZlm4dw4gPswPcSIZQmc2Zgnz7kmnOWB4IuMRlNj85O9HRoKG3gA/Y4zlruuz32Gv/YDWMXkwT5ZrEi7ZfBWYGzSeSTqVOIZc0kyeS3544shALiehcw235yaeSF/cfnznzvEDoCDyeQAkZPicS8E3OZf9O+mrr3uKf/SjbAMJ5wTWFABzFWw0KsSfXpX5IXt/qQTc/2bMiQTsi3L29Y4MZgImQrqJt8JHJs534AsWJy1TGTioX6+pTkSvAQvFQ8sYsTSVQDqwdulRdiujO7q+r/WQCKSx7N7bCXnic3ylDrVpkKGMA4x/6Yq/1zUazoU7yq48Hf1d3GwH1WlYH47LmrNEFdB+bXqj5xUOEQe/nErragQ=

        skip_cleanup: true
        draft: true
        on:
          tags: true

branches:
  only:
    - master
    - ci
    - "/^v\\d.*/"
    - "/^testing-ci\\.*/"

notifications:
  email:
    on_success: never
