[package]
name = "surface"
version = "0.2.3"
authors = ["Maximilian Luz <luzmaximilian@gmail.com>"]
description = "Control various aspects of Microsoft Surface devices on Linux from the Command-Line"

repository = "https://github.com/qzed/surface-control"
readme = "README.md"
license = "MIT"

edition = "2018"
build = "build.rs"

[dependencies]
clap = "2.33.0"
indoc = "0.3.4"
nix = "0.15.0"
failure = "0.1.5"

[build-dependencies]
clap = "2.33.0"
indoc = "0.3.4"

[profile.release]
lto = true
codegen-units = 1
