[package]
name = "surface"
version = "0.1.0"
authors = ["Maximilian Luz <luzmaximilian@gmail.com>"]
description = "Control various aspects of Microsoft Surface devices on Linux from the Command-Line"

repository = "https://github.com/qzed/surface-control"
readme = "README.md"
license = "MIT"

edition = "2018"

[dependencies]
clap = "2.33.0"
indoc = "0.3.1"
nix = "0.13.0"
