[package]
name = "surface"
version = "0.2.7"
authors = ["Maximilian Luz <luzmaximilian@gmail.com>"]
description = "Control various aspects of Microsoft Surface devices on Linux from the Command-Line"

repository = "https://github.com/linux-surface/surface-control"
readme = "README.md"
license = "MIT"

edition = "2018"
build = "build.rs"

[dependencies]
clap = "2.33.3"
indoc = "1.0.2"
nix = "0.18.0"
failure = "0.1.8"

[build-dependencies]
clap = "2.33.3"
indoc = "1.0.2"

[profile.release]
lto = true
codegen-units = 1
