[package]
name = "surface"
version = "0.4.0"
authors = ["Maximilian Luz <luzmaximilian@gmail.com>"]
description = "Control various aspects of Microsoft Surface devices on Linux from the Command-Line"

repository = "https://github.com/linux-surface/surface-control"
readme = "README.md"
license = "MIT"

edition = "2018"
build = "build.rs"

[dependencies]
anyhow = "1.0.38"
clap = "2.33.3"
indoc = "1.0.3"
nix = "0.20.0"
sdtx = { git = "https://github.com/linux-surface/libsurfacedtx", tag = "v0.1.0" }
serde = "1.0.124"
serde_json = "1.0.64"
thiserror = "1.0.24"
udev = "0.6.0"

[build-dependencies]
anyhow = "1.0.38"
clap = "2.33.3"
indoc = "1.0.3"
nix = "0.20.0"
sdtx = { git = "https://github.com/linux-surface/libsurfacedtx", tag = "v0.1.0" }
serde = "1.0.124"
serde_json = "1.0.64"
thiserror = "1.0.24"
udev = "0.6.0"

[profile.release]
lto = true
codegen-units = 1
