[package]
name = "surface"
version = "0.3.0"
authors = ["Maximilian Luz <luzmaximilian@gmail.com>"]
description = "Control various aspects of Microsoft Surface devices on Linux from the Command-Line"

repository = "https://github.com/linux-surface/surface-control"
readme = "README.md"
license = "MIT"

edition = "2018"
build = "build.rs"

[dependencies]
clap = "2.33.3"
indoc = "1.0.3"
nix = "0.20.0"
thiserror = "1.0.24"
anyhow = "1.0.38"
smallvec = "1.6.1"

[build-dependencies]
clap = "2.33.3"
indoc = "1.0.3"
nix = "0.20.0"
thiserror = "1.0.24"
anyhow = "1.0.38"
smallvec = "1.6.1"

[profile.release]
lto = true
codegen-units = 1
